### PR TITLE
update snakemake for newer versions of conda

### PR DESCRIPTION
**Pull request by scottdaniel**
* [x] I have run `bash tests/test.sh` on a local deployment and the tests passed successfully
* [NA] If this adds a new output file, I have added a check to tests/targets.txt
* [x] If this fixes a bug, I have added an appropriate test to tests/test.sh
* [NA] If this adds or modifies a rule that uses FASTQ files, the input accepts gzipped FASTQ and outputs gzipped FASTQ, or marks uncompressed FASTQ output as `temp`

-Made environment.yml get the latest version of snakemake which works with the latest version of conda (otherwise, when you run any extension that has --use-conda, it will fail when it tries "source activate")
-Added test for "--use-conda"

### CODE REVIEW

**Comment by ressy** [comment]
Thanks!  Good to have `--use-conda` in the test suite, I think.  Should we pin snakemake at a specific newer version or let it float at the latest?  (There may have been a reason for 4.8.1 until now but I'm not sure.)

**Comment by scottdaniel** [comment]
> Thanks! Good to have `--use-conda` in the test suite, I think. Should we pin snakemake at a specific newer version or let it float at the latest? (There may have been a reason for 4.8.1 until now but I'm not sure.)

Yeah, I guess pinning it at the exact version that is working would be good, I'll edit and re-commit

**Comment by scottdaniel** [comment]
Just a note, there is still a warning message `DeprecationWarning: 'source deactivate' is deprecated. Use 'conda deactivate'` because I couldn't figure out how to change the "source activate" in install.sh without breaking it

**Comment by ressy** [comment]
No worries, @eclarke noted the warnings in #198 already so we'll tidy that up at some point.

Erik, do you know of any potential problem for us in the 4 -> 5 major version switch for Snakemake?  Of course, ideally the tests will cover any possible scenario ;)  Skimming the [changelog](https://snakemake.readthedocs.io/en/stable/project_info/history.html) I just see two items labeled "This is a breaking change" since 4.8.1, one for the script directive and one for the directory marker function.  So I *think* we should be in the clear.

**Comment by ressy** [comment]
And just to double-check, this is merging into stable since it's a fix?  Or should we go to dev first?

**Comment by louiejtaylor** [comment]
Probably @eclarke has the final word but I can't see this breaking anything if we push directly into stable?

**Comment by eclarke** [comment]
if the tests pass, i’m good with it!

**Comment by ressy** [comment]
Speaking of tests, what's up with CircleCI?  I can't see any sign of a build matching this and it seems stuck on this side.  Am I missing anything over there?

**Comment by ressy** [comment]
I fetched @scottdaniel's fixes branch and then pushed it within this repo and that triggered a CircleCI build, at least: https://circleci.com/gh/sunbeam-labs/sunbeam/153.  Maybe I just didn't realize [how the integration works for forks](https://support.circleci.com/hc/en-us/articles/360008097173)?  But the pending status shown here is still blocking the merge.

**Comment by louiejtaylor** [comment]
Checking in--@ressy and @scottdaniel did y'all ever figure out why the tests didn't run for this PR?

**Comment by ressy** [comment]
@louiejtaylor no, I'm still confused on that.  It does list build 155 now for Scott's branch:

https://circleci.com/gh/sunbeam-labs/sunbeam/tree/scottdaniel-fixes

...but it does't seem to recognize it on this side.  I don't think it's a CircleCI issue since the build shows up and is passing but maybe a GitHub thing.

**Comment by ressy** [comment]
Agh now we've got an incompatibility with the latest MEGAHIT that's causing failures; see #213.  Might be best to settle that to fix existing tests and then figure out re-triggering an updated build here.

**Comment by ressy** [comment]
Merged separately in #215.  We got there eventually!  Thanks @scottdaniel.

**Pull request closed without merging**
